server:
  port: 8081

spring:
  application:
    name: order-service
  config:
    import: "configserver:http://localhost:8888"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"