server:
  port: 8080

spring:
  application:
    name: order-service

  # MySQL Database Connection
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: 7!X0rPX0H^hQnM#h8%K%

  # JPA Configurations
  jpa:
    hibernate:
      ddl-auto: update # Creates/updates tables automatically
    show-sql: true

  # RabbitMQ Connection (explicitly defined as per our contract)
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest