server:
  port: 8080

spring:
  application:
    name: client-application
  security:
    oauth2:
      client:
        registration:
          # Client registration for Client Credentials flow
          demo-client:
            client-id: demo-client
            client-secret: demo-secret
            authorization-grant-type: client_credentials
            scope: read,write
        provider:
          # OAuth2 provider configuration
          demo-client:
            token-uri: http://localhost:9000/oauth2/token

# Resource server configuration
resource-server:
  base-url: http://localhost:8090

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
