spring:
    application:
        name: authorization-server

server:
    port: 9000

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.security.oauth2: DEBUG
