server:
  port: 8080

spring:
  application:
    name: order-service

  # MySQL Database Connection
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: 7!X0rPX0H^hQnM#h8%K%

  # JPA Configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # RabbitMQ Connection
  rabbitmq:
    host: localhost